name = "PairArithmetic"
uuid = "bf5b35d8-838d-41b7-9f78-454e6b2b90d3"
keywords = ["Julia", "math", "floating-point", "extended-precision", "accuracy", "doubledouble"]
authors = ["Jeffrey Sarnoff <JeffreySarnoff@users.noreply.github.com>"]
license = "MIT"
desc = "Performant arithmetic with extra precision from error-free transformations."
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
ErrorfreeArithmetic = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
ErrorfreeArithmetic = "90fa49ef-747e-5e6f-a989-263ba693cf1a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Random", "Quadmath", "Test"]
benchmark = ["BenchmarkTools", "LinearAlgebra", "Statistics", "Quadmath", "RandomNumbers"]

[compat]
BenchmarkTools = "0, 1"
Documenter = "0, 1"
ErrorfreeArithmetic = "0, 1"
Polynomials = "0, 1"
Quadmath = "0, 1"
RandomNumbers = "0, 1"
LoopVectorization = "0, 1"
StructArrays = "0, 1"
julia = "1.5, 1.6, 1.7, 1.8, 1.9"
